# Generated by Django 5.1.4 on 2024-12-24 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['created_date'], 'verbose_name': 'ارتباط با ما', 'verbose_name_plural': 'ارتباط با ما'},
        ),
    ]
